version: '3.5'
services:
  php:
    container_name: php
    build:
      context: docker/docker
      dockerfile: php.Dockerfile
    volumes:
      - "./:/var/www/html"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/logs/nginx:/var/log/nginx/"
      - "./:/var/www/html"

  mysql:
    image: mysql:5.7
    container_name: container_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: 'on-failure'
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bt1"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
      - "./docker/config/mysql/custom.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/logs/mysql/query.log:/var/log/query.log"
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql